// User-submitted symptom report. Distinct from `Alert` — alerts are
// authored by jurisdiction admins (or auto-generated by the risk engine).
// Symptom reports are individual citizens reporting how they feel.
// Aggregated, they become a signal the risk engine can consume.
//
// Symptom vocabulary is the canonical catalog (the "Minimum Set of Key Data"
// standard) — see types/symptom-catalog.ts.

import type { SymptomCode } from "@/types/symptom-catalog";

// Reporter's self-assessed illness severity (not the same as the resource
// classifier's SymptomCategory).
export type SymptomSeverity = "mild" | "moderate" | "severe";

export interface SymptomReport {
  id: string;
  zip: string;
  county: "Pima" | "Maricopa";
  lat: number;
  lng: number;
  symptoms: SymptomCode[];
  severity: SymptomSeverity;
  reportedAt: string;
}

export interface ZipCentroid {
  zip: string;
  county: "Pima" | "Maricopa";
  label: string;
  lat: number;
  lng: number;
}

// Approximate centroids for visualization. NOT authoritative — replace with
// Census ZCTA data when we need real geographic accuracy.
export const AZ_ZIP_CENTROIDS: ZipCentroid[] = [
  // --- Maricopa (Phoenix metro) ---
  { zip: "85003", county: "Maricopa", label: "Phoenix Downtown", lat: 33.4585, lng: -112.082 },
  { zip: "85008", county: "Maricopa", label: "Phoenix East", lat: 33.4762, lng: -112.0252 },
  { zip: "85013", county: "Maricopa", label: "Phoenix Midtown", lat: 33.5101, lng: -112.081 },
  { zip: "85018", county: "Maricopa", label: "Arcadia", lat: 33.4953, lng: -111.9961 },
  { zip: "85021", county: "Maricopa", label: "Phoenix North", lat: 33.553, lng: -112.081 },
  { zip: "85032", county: "Maricopa", label: "Phoenix Paradise Valley", lat: 33.6232, lng: -112.0337 },
  { zip: "85033", county: "Maricopa", label: "Phoenix Maryvale", lat: 33.506, lng: -112.2138 },
  { zip: "85044", county: "Maricopa", label: "Ahwatukee", lat: 33.338, lng: -111.989 },
  { zip: "85201", county: "Maricopa", label: "Mesa", lat: 33.4329, lng: -111.8331 },
  { zip: "85204", county: "Maricopa", label: "Mesa Southeast", lat: 33.3958, lng: -111.7846 },
  { zip: "85226", county: "Maricopa", label: "Chandler", lat: 33.3225, lng: -111.942 },
  { zip: "85251", county: "Maricopa", label: "Scottsdale", lat: 33.4925, lng: -111.9258 },
  { zip: "85281", county: "Maricopa", label: "Tempe", lat: 33.4255, lng: -111.94 },
  { zip: "85301", county: "Maricopa", label: "Glendale", lat: 33.5386, lng: -112.186 },
  { zip: "85308", county: "Maricopa", label: "Glendale North", lat: 33.651, lng: -112.167 },
  { zip: "85338", county: "Maricopa", label: "Goodyear", lat: 33.4356, lng: -112.3576 },
  { zip: "85345", county: "Maricopa", label: "Peoria", lat: 33.5806, lng: -112.2374 },

  // --- Pima (Tucson metro) ---
  { zip: "85701", county: "Pima", label: "Tucson Downtown", lat: 32.2226, lng: -110.9747 },
  { zip: "85705", county: "Pima", label: "Tucson North", lat: 32.2787, lng: -110.9747 },
  { zip: "85706", county: "Pima", label: "Tucson South", lat: 32.1483, lng: -110.9492 },
  { zip: "85710", county: "Pima", label: "Tucson East", lat: 32.2227, lng: -110.8281 },
  { zip: "85713", county: "Pima", label: "Tucson Southwest", lat: 32.1957, lng: -110.9831 },
  { zip: "85716", county: "Pima", label: "Tucson Central", lat: 32.2425, lng: -110.9156 },
  { zip: "85718", county: "Pima", label: "Catalina Foothills", lat: 32.3267, lng: -110.9156 },
  { zip: "85719", county: "Pima", label: "U of A", lat: 32.2502, lng: -110.9495 },
  { zip: "85730", county: "Pima", label: "Tucson East", lat: 32.1828, lng: -110.8004 },
  { zip: "85737", county: "Pima", label: "Oro Valley", lat: 32.417, lng: -110.9645 },
  { zip: "85741", county: "Pima", label: "Tucson Northwest", lat: 32.329, lng: -111.053 },
  { zip: "85745", county: "Pima", label: "Tucson West", lat: 32.2455, lng: -111.0379 },
  { zip: "85747", county: "Pima", label: "Vail", lat: 32.0775, lng: -110.7158 },
];
